<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ZIPLBLRSY191" ignored="0" name="All API Test Cases" tests="11" failures="4" timestamp="22 Aug 2018 12:41:31 GMT" time="8.779" errors="0">
  <testcase name="validateDelete" time="3.634" classname="com.testcases.reqres.SimpleDelete"/>
  <testcase name="GetWeatherDetails" time="0.693" classname="com.testcases.reqres.SimpleGetNotFound"/>
  <testcase name="GetWeatherDetails" time="0.66" classname="com.testcases.reqres.SimpleGetTest"/>
  <testcase name="GetWeatherDetails" time="1.322" classname="com.testcases.reqres.SimplePostTest"/>
  <testcase name="validateDelete" time="0.673" classname="com.testcases.reqres.SimplePutTest"/>
  <testcase name="validateSuccessful" time="0.695" classname="com.testcases.reqres.UnthenticationSuccessful"/>
  <testcase name="validateUnsuccessful" time="0.689" classname="com.testcases.reqres.UnthenticationUnSuccessful"/>
  <testcase name="f" time="0.156" classname="com.testcases.reqres.PostCall">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
at com.testcases.reqres.PostCall.f(PostCall.java:26)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="g" time="0.08" classname="com.testcases.reqres.PostCall">
    <failure type="java.lang.AssertionError" message="expected [201] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [404]
at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
at com.testcases.reqres.PostCall.g(PostCall.java:38)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- g -->
  <testcase name="successFul" time="0.078" classname="com.testcases.reqres.SuccessAuthetication">
    <failure type="java.lang.AssertionError" message="expected [201] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [404]
at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
at com.testcases.reqres.SuccessAuthetication.successFul(SuccessAuthetication.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- successFul -->
  <testcase name="unSuccessFul" time="0.066" classname="com.testcases.reqres.SuccessAuthetication">
    <failure type="java.lang.AssertionError" message="expected [400] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [404]
at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
at com.testcases.reqres.SuccessAuthetication.unSuccessFul(SuccessAuthetication.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- unSuccessFul -->
</testsuite> <!-- All API Test Cases -->
