<html>
<head>
<title>TestNG:  All API Test Cases</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>All API Test Cases</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>7/4/0</td>
</tr><tr>
<td>Started on:</td><td>Wed Aug 22 18:11:23 IST 2018</td>
</tr>
<tr><td>Total time:</td><td>8 seconds (8779 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.testcases.reqres.PostCall.f()'><b>f</b><br>Test class: com.testcases.reqres.PostCall<br>Test method: This test case for get request</td>
<td><div><pre>java.lang.AssertionError: expected [200] but found [404]
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.PostCall.f(PostCall.java:26)
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1658785779", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1658785779'><pre>java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.PostCall.f(PostCall.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.testcases.reqres.PostCall@26a7b76d</td></tr>
<tr>
<td title='com.testcases.reqres.PostCall.g()'><b>g</b><br>Test class: com.testcases.reqres.PostCall<br>Test method: this test case for post request</td>
<td><div><pre>java.lang.AssertionError: expected [201] but found [404]
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.PostCall.g(PostCall.java:38)
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1951500432", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1951500432'><pre>java.lang.AssertionError: expected [201] but found [404]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.PostCall.g(PostCall.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.testcases.reqres.PostCall@26a7b76d</td></tr>
<tr>
<td title='com.testcases.reqres.SuccessAuthetication.successFul()'><b>successFul</b><br>Test class: com.testcases.reqres.SuccessAuthetication<br>Test method: this test case for post request with correct credential and verify is it creating token or not</td>
<td><div><pre>java.lang.AssertionError: expected [201] but found [404]
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.SuccessAuthetication.successFul(SuccessAuthetication.java:23)
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace930317866", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace930317866'><pre>java.lang.AssertionError: expected [201] but found [404]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.SuccessAuthetication.successFul(SuccessAuthetication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.testcases.reqres.SuccessAuthetication@4abdb505</td></tr>
<tr>
<td title='com.testcases.reqres.SuccessAuthetication.unSuccessFul()'><b>unSuccessFul</b><br>Test class: com.testcases.reqres.SuccessAuthetication<br>Test method: this test case for post request with incorrect credential and verify is it sending error message or not</td>
<td><div><pre>java.lang.AssertionError: expected [400] but found [404]
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.SuccessAuthetication.unSuccessFul(SuccessAuthetication.java:35)
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace167693809", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace167693809'><pre>java.lang.AssertionError: expected [400] but found [404]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)
	at com.testcases.reqres.SuccessAuthetication.unSuccessFul(SuccessAuthetication.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.testcases.reqres.SuccessAuthetication@4abdb505</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.testcases.reqres.SimpleGetNotFound.GetWeatherDetails()'><b>GetWeatherDetails</b><br>Test class: com.testcases.reqres.SimpleGetNotFound<br>Test method: This test case not found the resource</td>
<td></td>
<td>0</td>
<td>com.testcases.reqres.SimpleGetNotFound@5bb21b69</td></tr>
<tr>
<td title='com.testcases.reqres.SimpleGetTest.GetWeatherDetails()'><b>GetWeatherDetails</b><br>Test class: com.testcases.reqres.SimpleGetTest<br>Test method: This test case for validate the get resource</td>
<td></td>
<td>0</td>
<td>com.testcases.reqres.SimpleGetTest@6b9651f3</td></tr>
<tr>
<td title='com.testcases.reqres.SimplePostTest.GetWeatherDetails()'><b>GetWeatherDetails</b><br>Test class: com.testcases.reqres.SimplePostTest<br>Test method: This test case for validate post call</td>
<td></td>
<td>1</td>
<td>com.testcases.reqres.SimplePostTest@38bc8ab5</td></tr>
<tr>
<td title='com.testcases.reqres.SimpleDelete.validateDelete()'><b>validateDelete</b><br>Test class: com.testcases.reqres.SimpleDelete<br>Test method: This test case for validate delete resource</td>
<td></td>
<td>3</td>
<td>com.testcases.reqres.SimpleDelete@587d1d39</td></tr>
<tr>
<td title='com.testcases.reqres.SimplePutTest.validateDelete()'><b>validateDelete</b><br>Test class: com.testcases.reqres.SimplePutTest<br>Test method: This test case for validate put configuration</td>
<td></td>
<td>0</td>
<td>com.testcases.reqres.SimplePutTest@687080dc</td></tr>
<tr>
<td title='com.testcases.reqres.UnthenticationSuccessful.validateSuccessful()'><b>validateSuccessful</b><br>Test class: com.testcases.reqres.UnthenticationSuccessful<br>Test method: this test vaildate the suceessful authentication</td>
<td></td>
<td>0</td>
<td>com.testcases.reqres.UnthenticationSuccessful@23d2a7e8</td></tr>
<tr>
<td title='com.testcases.reqres.UnthenticationUnSuccessful.validateUnsuccessful()'><b>validateUnsuccessful</b><br>Test class: com.testcases.reqres.UnthenticationUnSuccessful<br>Test method: This test case valiadate the unsuceessful attempt</td>
<td></td>
<td>0</td>
<td>com.testcases.reqres.UnthenticationUnSuccessful@7a9273a8</td></tr>
</table><p>
</body>
</html>